/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogodaforca;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.OptionPaneUI;

/**
 *
 * @author Thiago
 */
public class Tela extends javax.swing.JFrame {
    private JLabel posicao_letra[];
    private Palavra palavra;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnl_forca = new javax.swing.JPanel();
        pnl_superior_direito = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cmp_letras_digitadas = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        pnl_inferior_direito = new javax.swing.JPanel();
        pnl_palavras = new javax.swing.JPanel();
        cmp_entrada_letras = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_ok_testa_letra = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btn_nova_partida = new javax.swing.JMenuItem();
        btn_recordes = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        btn_sair = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {260, 350};
        jPanel1Layout.rowHeights = new int[] {200, 250};
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout pnl_forcaLayout = new javax.swing.GroupLayout(pnl_forca);
        pnl_forca.setLayout(pnl_forcaLayout);
        pnl_forcaLayout.setHorizontalGroup(
            pnl_forcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        pnl_forcaLayout.setVerticalGroup(
            pnl_forcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(pnl_forca, gridBagConstraints);

        jScrollPane1.setViewportView(cmp_letras_digitadas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Letras digitadas que não contém");

        javax.swing.GroupLayout pnl_superior_direitoLayout = new javax.swing.GroupLayout(pnl_superior_direito);
        pnl_superior_direito.setLayout(pnl_superior_direitoLayout);
        pnl_superior_direitoLayout.setHorizontalGroup(
            pnl_superior_direitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_superior_direitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_superior_direitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_superior_direitoLayout.setVerticalGroup(
            pnl_superior_direitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_superior_direitoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(pnl_superior_direito, gridBagConstraints);

        pnl_palavras.setLayout(new java.awt.GridLayout(2, 4, 2, 2));

        cmp_entrada_letras.setToolTipText("");

        jLabel2.setText("Digite uma letra ou a palavra inteira:");

        btn_ok_testa_letra.setText("Ok");
        btn_ok_testa_letra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ok_testa_letraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_inferior_direitoLayout = new javax.swing.GroupLayout(pnl_inferior_direito);
        pnl_inferior_direito.setLayout(pnl_inferior_direitoLayout);
        pnl_inferior_direitoLayout.setHorizontalGroup(
            pnl_inferior_direitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_inferior_direitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_inferior_direitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_inferior_direitoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnl_palavras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(pnl_inferior_direitoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_inferior_direitoLayout.createSequentialGroup()
                        .addComponent(cmp_entrada_letras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ok_testa_letra)
                        .addContainerGap())))
        );
        pnl_inferior_direitoLayout.setVerticalGroup(
            pnl_inferior_direitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_inferior_direitoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_palavras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_inferior_direitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmp_entrada_letras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ok_testa_letra))
                .addGap(107, 107, 107))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(pnl_inferior_direito, gridBagConstraints);

        jMenu1.setText("Jogo");

        btn_nova_partida.setText("Nova Partida");
        btn_nova_partida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nova_partidaActionPerformed(evt);
            }
        });
        jMenu1.add(btn_nova_partida);

        btn_recordes.setText("Recordes");
        jMenu1.add(btn_recordes);
        jMenu1.add(jSeparator2);

        btn_sair.setText("Sair");
        jMenu1.add(btn_sair);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Palavras");

        jMenuItem5.setText("Nova Palavra");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btn_ok_testa_letraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ok_testa_letraActionPerformed
        String str;
        str = cmp_entrada_letras.getText();
        if(str.length()==1) {
            if(palavra.LetraExiste(str.charAt(0))==0) cmp_letras_digitadas.setText(cmp_letras_digitadas.getText() + " " + str);
            else imprimePalavra();
        }
        cmp_entrada_letras.setText("");
    }//GEN-LAST:event_btn_ok_testa_letraActionPerformed

    private void btn_nova_partidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nova_partidaActionPerformed
        
        /*** APENAS PARA TESTES ***
        palavra = new Palavra(JOptionPane.showInputDialog("Digita a palavra:"));
        atualizaCampoPalavras();
        */
    }//GEN-LAST:event_btn_nova_partidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btn_nova_partida;
    private javax.swing.JButton btn_ok_testa_letra;
    private javax.swing.JMenuItem btn_recordes;
    private javax.swing.JMenuItem btn_sair;
    private javax.swing.JTextField cmp_entrada_letras;
    private javax.swing.JTextPane cmp_letras_digitadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPanel pnl_forca;
    private javax.swing.JPanel pnl_inferior_direito;
    private javax.swing.JPanel pnl_palavras;
    private javax.swing.JPanel pnl_superior_direito;
    // End of variables declaration//GEN-END:variables
    public void atualizaCampoPalavras(){
        int i,l;
        l = palavra.tamanho();
        pnl_palavras.removeAll();
        posicao_letra = new JLabel[l];
        pnl_palavras.setPreferredSize(new Dimension(18*l,20));
        pnl_palavras.setLayout(new java.awt.GridLayout(1,l,2,2));//Define se em GridLayout: Número de Linhas,Número de Letras como número de colunas, espaço horizontal e vertical 
        
        for(i=0;i<l;i++){
            posicao_letra[i] = new JLabel();
            posicao_letra[i].setText(" ");//String.valueOf(palavra.charAt(i))
            posicao_letra[i].setBackground(Color.WHITE);
            posicao_letra[i].setOpaque(!palavra.getLetra(i).equals(" "));
            posicao_letra[i].setVerticalAlignment(javax.swing.SwingConstants.CENTER);
            posicao_letra[i].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            pnl_palavras.add(posicao_letra[i]);
        }
        pnl_inferior_direito.doLayout();
        pnl_palavras.doLayout();
    }
    public void imprimePalavra(){
        int i;
        for(i=0;i<palavra.tamanho();i++){
            if(palavra.getPosicao(i)) {
                posicao_letra[i].setText(palavra.getLetra(i));
            }
        }
    }
}
